# Generated by Django 4.2.1 on 2023-05-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_data',
            new_name='post_date',
        ),
    ]
